dataset:
  type: "BVILowLight"
  train_file: "../low_light_data_capture/train_list.txt"
  val_file: "../low_light_data_capture/test_list.txt"
  root_distorted: "../low_light_data_capture/input"
  root_restored: "../low_light_data_capture/gt"
  image_size: 512
  num_frames: 5
  num_workers: 4
  aug_topleft: False

model:
  network: "STASUNet"
  patch_size: 4 
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 16
  window_size: 8
  patch_norm: True
  deformable_groups: 8
  num_extract_block: 5
  num_reconstruct_block: 10
  hr_in: True
  depths: [8, 8, 8, 8]
  num_heads: [8, 8, 8, 8]

training:
  batch_size: 4
  


