dataset:
  type: "BVILowLight"
  train_file: "/home/gf19473/datasets/lowlight_dataset/train_list.txt"
  val_file: "/home/gf19473/datasets/lowlight_dataset/test_list.txt"
  root_distorted: "/home/gf19473/datasets/lowlight_dataset/input"
  root_restored: "/home/gf19473/datasets/lowlight_dataset/gt"
  image_size: 512
  num_frames: 5
  num_workers: 0
  aug_topleft: False

model:
  network: "STASUNet"
  patch_size: 4 
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 16
  embed_dim: 16
  window_size: 8
  patch_norm: True
  deformable_groups: 8
  num_extract_block: 5
  num_reconstruct_block: 10
  hr_in: True
  depths: [8, 8, 8, 8]
  num_heads: [8, 8, 8, 8]

training:
  batch_size: 1
  maxepoch: 25
  lr: 0.0001
  eval_frequency: 1
  


